[*] Start mutation process:
   - targets: factorial.py
   - tests: ts-3-5/test_3-5_0-4_133.py
[*] 4 tests passed:
   - test_3-5_0-4_133 [0.12004 s]
[*] Start mutants generation and execution:
   - [#   1] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x / y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14656 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
   - [#   2] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x // y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15077 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
   - [#   3] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x ** y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15028 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
   - [#   4] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x * y)), range(1, n - 1))
--------------------------------------------------------------------------------
[0.15269 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
   - [#   5] COI factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if not (n <= 0):
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14322 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
   - [#   6] ROR factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if n >= 0:
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14329 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
   - [#   7] ROR factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if n < 0:
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15179 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   8] SDL factorial: 
--------------------------------------------------------------------------------
  12:         of 0 or less will output 0.
  13:     '''
  14:     
  15:     if n <= 0:
- 16:         return 0
+ 16:         pass
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14599 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   9] SDL factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     pass
--------------------------------------------------------------------------------
[0.14495 s] killed by ts-3-5/test_3-5_0-4_133.py::test_factorial_with_positive_number

def test_factorial_with_positive_number():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_133.py:12: AssertionError
[*] Mutation score [1.55073 s]: 100.0%
   - all: 9
   - killed: 7 (77.8%)
   - survived: 0 (0.0%)
   - incompetent: 2 (22.2%)
   - timeout: 0 (0.0%)
