[*] Start mutation process:
   - targets: factorial.py
   - tests: ts-3-5/test_3-5_0-9_282.py
[*] 4 tests passed:
   - test_3-5_0-9_282 [0.12991 s]
[*] Start mutants generation and execution:
   - [#   1] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x / y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15106 s] killed by ts-3-5/test_3-5_0-9_282.py::test_factorial_with_positive_input

def test_factorial_with_positive_input():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-9_282.py:18: AssertionError
   - [#   2] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x // y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15457 s] killed by ts-3-5/test_3-5_0-9_282.py::test_factorial_with_positive_input

def test_factorial_with_positive_input():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-9_282.py:18: AssertionError
   - [#   3] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x ** y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15479 s] killed by ts-3-5/test_3-5_0-9_282.py::test_factorial_with_positive_input

def test_factorial_with_positive_input():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-9_282.py:18: AssertionError
   - [#   4] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x * y)), range(1, n - 1))
--------------------------------------------------------------------------------
[0.15431 s] killed by ts-3-5/test_3-5_0-9_282.py::test_factorial_with_positive_input

def test_factorial_with_positive_input():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-9_282.py:18: AssertionError
   - [#   5] COI factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if not (n <= 0):
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15633 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   6] ROR factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if n >= 0:
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14578 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   7] ROR factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if n < 0:
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15507 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   8] SDL factorial: 
--------------------------------------------------------------------------------
  12:         of 0 or less will output 0.
  13:     '''
  14:     
  15:     if n <= 0:
- 16:         return 0
+ 16:         pass
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14169 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   9] SDL factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     pass
--------------------------------------------------------------------------------
[0.15315 s] killed by ts-3-5/test_3-5_0-9_282.py::test_factorial_with_positive_input

def test_factorial_with_positive_input():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-9_282.py:18: AssertionError
[*] Mutation score [1.60065 s]: 100.0%
   - all: 9
   - killed: 5 (55.6%)
   - survived: 0 (0.0%)
   - incompetent: 4 (44.4%)
   - timeout: 0 (0.0%)
